pages:
  stage: deploy
  script:
  - pip install -U jupyter-book==0.10.2
  - jupyter-book build .
  - mkdir -p public
  - cp -r _build/html/* public/
  artifacts:
    paths:
    - public
  only:
  - master
