deploy:
  stage: deploy
  script:
  - apt update && apt install -y python3-pip  
  - pip3 install -r requirements.txt
  
  - jupyter-book build --all .
  
  - rm -rf /srv/gitlab/pages/$CI_PROJECT_NAME
  - mkdir -p /srv/gitlab/pages/$CI_PROJECT_NAME
  - cp -r _build/html/* /srv/gitlab/pages/$CI_PROJECT_NAME
  only:
  - master

