deploy:
  stage: deploy
  script:
  - apt update && apt install -y python3-pip  
  - pip3 install jupyter-book==0.10.2 numpy matplotlib pandas sklearn seaborn
  
  - jupyter-book build .
  
  - rm -rf /srv/gitlab/pages/$CI_PROJECT_NAME
  - mkdir -p /srv/gitlab/pages/$CI_PROJECT_NAME
  - cp -r _build/html/* /srv/gitlab/pages/$CI_PROJECT_NAME
  only:
  - master

